### ISSUE TITLE
Can't display Just thetime

### ISSUE THREAD

**Issue by henryavila** [techouse/intl-date-time#27]
HI. If I use:

```
IntlDateTime::make('Hora', 'time')
                    ->hideUserTimeZone()
                    ->withTimeShort()
```

Or even:
```
IntlDateTime::make('Hora', 'time')
                    ->timeFormat('HH:mm:ss')
                    ->withTimeShort()
```

It always select a date and the time.
It should allow to select just the time.

**Comment by techouse** [comment]
Hi and no. This is a date/time picker and even the methods you explicitly use have `with` in their name not `only`. I do not intend to develop just a time picker. There are many out there and time is not one of these things that need internationalisation since everyone pretty much uses the same format and annotation.

I updated the README to make this clearer.
