### ISSUE TITLE
Implement different Dateformat

### ISSUE THREAD

**Issue by Jun-ocx** [techouse/intl-date-time#45]
in my project, I want it to show in the format as "MM/DD/YYYY" in US
I've tried

```
->format('MM-DD-YYYY)
->format('MM/DD/YYYY)
->dateFormat('MM-DD-YYYY')
->dateFormat('MM/DD/YYYY')
```

none of them is working

->dateFormat('MM/DD/YYYY') seems to work but gives an error message: The Expires must be in the format dd/MM/yyyy

![Screen Shot 2021-01-19 at 1 46 28 PM](https://user-images.githubusercontent.com/55770199/105096992-bda30280-5a5c-11eb-83d8-937742207367.png)

also when I try to use it with ->minDate(Carbon::now()), it gives the totally wrong date to start with

![Screen Shot 2021-01-19 at 1 48 08 PM](https://user-images.githubusercontent.com/55770199/105097148-f93dcc80-5a5c-11eb-9d03-3407afe25d68.png)

**Comment by techouse** [comment]
Hey!

As this module extracts locales from MomentJS it [only supports locales that MomentJS supports](https://github.com/moment/moment/tree/2.29.1/src/locale) and [en-US is not one of them](https://github.com/moment/moment/issues/3624). This is a known bug of MomentJS that hasn't been fixed in over 2 years.
