### ISSUE TITLE
96 validation_locale files importing... It's normal ?

### ISSUE THREAD

**Issue by wemersonrv** [techouse/intl-date-time#8]
**Version: ^1.2.3**

After recent updates, it's imports almost 100 files for validation locales files (`validation_locales_01` to `validation_locales_96`)... it's importing individual files because i'm in development mode ? When generate a production build will generate only one import file ?

It's a lot of files...

**Comment by techouse** [comment]
Yes it's perfectly normal. It uses [dynamic importing](https://github.com/techouse/intl-date-time/blob/master/resources/js/components/IntlDateTimePicker.vue#L162) and [code splitting](https://webpack.js.org/guides/code-splitting/). Then those locale files are fed to the plugin using Nova's [`FieldServiceProvider`](https://github.com/techouse/intl-date-time/blob/master/src/FieldServiceProvider.php#L24)

It had to be done this way in order to keep the `field.js` file small. Otherwise it would have been 1MB+. 

And no in production it will still generate multiple files. This is already a production build. If you want you can of course limit the error locales by forking the repo and eliminating those which you don't want. Another way that would probably also work would be deleting them from the production [`dist/validation_locales`](https://github.com/techouse/intl-date-time/tree/master/dist/js/validation_locales) folder on your machine / production server.

However I will take a look at some stripping sort of functionality in order to limit the extension to only the locales used.

**Comment by techouse** [comment]
OK, optimised now in [v1.2.4](https://github.com/techouse/intl-date-time/commit/cc97d1e633c4e25861690d7739280ac246390741) 😇
